name: app1 pipeline 
on:
  workflow_call:
    inputs:
      run_permit:
        required: true
        type: string

    
env:
  image_name: app1
  registry: atlas
  app_name: app1
  password: ${{ secrets.G_PASS}}
  user: ${{ secrets.G_USER}}
  domain: ${{ secrets.G_DOMAIN}}
  repo_token: ${{ secrets.REPO_TOKEN}}
  


jobs:
  build-app1:
    if: ${{ inputs.run_permit == 'true' }}
    runs-on: build
    outputs: 
      image_tag: ${{ steps.build_push_app1.outputs.image_tag}}
    env:
      repository: atlas/build_repo2
      workdir: app1dir
      dockerfile_path: Dockerfile
   
    steps:

      - name: Check out code with build action 
        uses: https://gitea.com/actions/checkout@v3
        with:
          repository: ${{ env.repository }}
          ref: ${{ gitea.ref }} 
          token: ${{ env.repo_token }}

      - name: Build and push app1 image
        id: build_push_app1
        uses: ./.gitea/actions/build_action
        with: 
          image_name: ${{ env.image_name }}
          registry: ${{ env.registry }}
          app_name: ${{ env.app_name }}
          workdir: ${{ env.workdir }}
          dockerfile_path: ${{ env.dockerfile_path }}
          domain: ${{ env.domain }}
          user: ${{ env.user }}
          password: ${{ env.password }}
          repo_token: ${{ env.repo_token }}
          repository: ${{ env.repository }}
          build_branch: ${{ github.ref_name }}

  deploy-app1:
    runs-on: build
    needs: build-app1
    uses: ./.gitea/workflows/trigger-deploy.yaml
    secrets: inherit
    with: 
      build_branch: ${{ github.ref_name }}
      image_tag: ${{ needs.build-app1.outputs.image_tag }}
      run_permit: ${{ inputs.run_permit }}
      app_name: ${{ env.app_name }}
      registry: ${{ env.registry }}
      build_result: ${{ needs.build-app1.result }}
